name: game_flutter
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.0-209.1.beta

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_screenutil: ^5.9.3
  provider: ^6.1.2
  shared_preferences: ^2.5.3
  audioplayers: ^6.4.0
  animations: ^2.0.11
  flutter_spinkit: ^5.2.1
  get_it: ^8.0.3
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  fluttertoast: ^8.2.12

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true


  assets:
    - assets/backgrounds/
    - assets/icons/
    - assets/audios/
